name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install PHP Action
      uses: shivammathur/setup-php@1.3.6
      with:
        php-version: 7.3
    - name: Install Composer dependencies
      run: composer install
    - name: Run lint command
      run: composer lint
